### ISSUE TITLE
Исправить баг с не изменением two_sided на проде

### ISSUE THREAD

**Issue by Annndruha** [profcomff/print-api#19]
Есть попробовать patch запросом изменить состояние two_sided  с True на False
то состояние не меняется.

На тесте пофикшено, нужно проверить что на проде тоже пофикшено

**Comment by grigoriev-semyon** [comment]
Исправлено? в #45

**Comment by grigoriev-semyon** [comment]
@dyakovri @Annndruha

**Comment by dyakovri** [comment]
Да там исправлено, вопрос катнули ли на прод

**Comment by Annndruha** [comment]
Катнули, отрабатывает нормально
